name: "Deploy to staging"

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.STAGING_FTP_USER }}
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          server-dir: theme/hsfk/
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            documentation/
            .yarn/
            .github/
